export const RMQ_EVENTS = {
  EMAIL_VERIFICATION: 'email.verification',
  // PASSWORD_RESET = 'password.reset',
  // USER_SIGNUP = 'user.signup',
  // USER_LOGIN = 'user.login',
  // USER_LOGOUT = 'user.logout',
  // USER_PROFILE_UPDATE = 'user.profile.update',
  // USER_DELETED = 'user.deleted',
  // USER_AUTHENTICATED = 'user.authenticated',
  // USER_EMAIL_VERIFIED = 'user.email_verified',
  // USER_PASSWORD_RESET = 'user.password_reset',
  // USER_PASSWORD_CHANGED = 'user.password_changed',
  // USER_ACCOUNT_LOCKED = 'user.account_locked',
  // USER_ACCOUNT_UNLOCKED = 'user.account_unlocked',
  // USER_ACCOUNT_SUSPENDED = 'user.account_suspended',
  // USER_ACCOUNT_REACTIVATED = 'user.account_reactivated',
  // USER_ROLE_ASSIGNED = 'user.role_assigned',
  // USER_ROLE_REMOVED = 'user.role_removed',
  // USER_PERMISSIONS_UPDATED = 'user.permissions_updated',
  // USER_PROFILE_PICTURE_UPDATED = 'user.profile_picture_updated',
  // USER_TWO_FACTOR_ENABLED = 'user.two_factor_enabled',
  // USER_TWO_FACTOR_DISABLED = 'user.two_factor_disabled',
  // USER_SESSION_CREATED = 'user.session.created',
  // USER_SESSION_DELETED = 'user.session.deleted',
  // USER_SESSION_EXPIRED = 'user.session.expired',
};
