export enum ClientEvents {
  CLIENT_CREATED = 'user.created',
  USER_UPDATED = 'user.updated',
  USER_DELETED = 'user.deleted',
  USER_PROFILE_UPDATED = 'user.profile.updated',
  USER_EMAIL_VERIFIED = 'user.email.verified',
  USER_EMAIL_VERIFICATION_REQUESTED = 'user.email.verification.requested',
  USER_AUTHENTICATED = 'user.authenticated',
  USER_PASSWORD_RESET_REQUESTED = 'user.password.reset.requested',
  USER_PASSWORD_RESET = 'user.password.reset',
  USER_PASSWORD_CHANGED = 'user.password.changed',
  USER_ACCOUNT_LOCKED = 'user.account.locked',
  USER_ACCOUNT_UNLOCKED = 'user.account.unlocked',
  USER_ACCOUNT_SUSPENDED = 'user.account.suspended',
  USER_ACCOUNT_REACTIVATED = 'user.account.reactivated',
  USER_ROLE_ASSIGNED = 'user.role.assigned',
  USER_ROLE_REMOVED = 'user.role.removed',
  USER_PERMISSIONS_UPDATED = 'user.permissions.updated',
  USER_PROFILE_PICTURE_UPDATED = 'user.profile_picture.updated',
  USER_TWO_FACTOR_ENABLED = 'user.two_factor.enabled',
  USER_TWO_FACTOR_DISABLED = 'user.two_factor.disabled',
  USER_SESSION_CREATED = 'user.session.created',
  USER_SESSION_DELETED = 'user.session.deleted',
  USER_SESSION_EXPIRED = 'user.session.expired',
  USER_NEW_DEVICE_LOGIN = 'user.new_device.login',
  USER_DEACTIVATED = 'user.deactivated',
}
